### ISSUE TITLE
Why the translations has stopped? / Miért nincsenek új fordítások

### ISSUE THREAD

**Issue by balazsorban44** [reactjs/hu.reactjs.org#141]
If you end up here, you might be wondering why did the translations have stopped?

I mentioned it here before: https://github.com/reactjs/hu.reactjs.org/issues/1#issuecomment-787459722, but I copy it here as well:

> The React docs is getting a big overhaul as I understood from reactjs/reactjs.org#3308 and it is said that the content will be completely rewritten (reactjs/reactjs.org#3308 (comment)). This is the main reason I did not give this project as much attention as before. That said, the current format is hopefully still useful for many, and I still hope that the already translated content can help us in some way when translating the new content as well.

I have the intention to jump on translating again when the new documentation is ready, until then, I am in a low-effort maintenance mode. If you think there is something urgent to fix though, feel free to reach out!

---

Tehát ha ezt olvasod, akkor valószínűleg azon agyalsz, hogy miért álltak le a fordítások? A valóság az, hogy a React csapata úgy döntött, hogy át szeretnék írni az egész dokumentációt az alapoktól. A legvalószínűbb ok az lehet, hogy a Horgok (hooks) még mindig "újdonságként" vannak emlegetve, de ez már nem igaz. Az igazság az, hogy a Horgok sokkal fontosabbá váltak mint az Osztály komponensek (class components). Emiatt úgy döntöttem, hogy egy időre szüneteltetem az új fordításokat, és egy alapszintű karbantartó üzemmódba állok a repo-n. Ha viszont bárkinek bármilyen észrevétele van amit sürgős lenne kijavítani, nyugodtan vegye fel a kapcsolatot velem!

**Comment by balazsorban44** [comment]
Translating can be resumed, please reach out to me, if interested!

https://github.com/reactjs/hu.reactjs.org/issues/1#issuecomment-985138032

**Comment by gaearon** [comment]
https://github.com/reactjs/hu.react.dev/issues/219
