### ISSUE TITLE
Search results point to netlify build url

### ISSUE THREAD

**Issue by punkah** [reactjs/hu.reactjs.org#61]
We now have a website at https://hu.reactjs.org/ but Algolia Crawling is still configured to crawl the Netlify URL.

**Comment by balazsorban44** [comment]
I am going to fix this, I sent a new request to the Algolia Team for an API key for the domain http://hu.reactjs.org/ Should only take a few days.

**Comment by balazsorban44** [comment]
The API key did not change, but I had to change some URLs in the linked PR. The search results should be OK soon.
