### ISSUE TITLE
Rating under each docs page is not translated

### ISSUE THREAD

**Issue by kac5a** [reactjs/hu.reactjs.org#85]
Az "Is this page useful?" és az utána megjelenő "Thanks for letting us know!" szövegek nincsenek lefordítva.

Egy local branch-ben javítottam, viszont nincs jogosultságom felpusholni a change-eket.

Tudnátok adni contributor jogot?

A Hacktoberfest programba ez a repo beleszámít?

**Comment by balazsorban44** [comment]
A repo-hoz közvetlenül csak maintainer kaphat contributor jogosultságot. Azt ajánlom, hogy fork-old a repot, és abból tudni fogsz nyitni egy PRt. Tudtommal nem korlátozzuk a hacktoberfestet.
